import React, { useEffect } from 'react';
import { useCrm } from '../context/CrmContext';
import SafeIcon from '../common/SafeIcon';
import * as FiIcons from 'react-icons/fi';
import { supabase, logToAsguardDLQ } from '../lib/supabase';
import { toast } from 'react-toastify';
import { activityService } from '../services/activityService';
import { swarmService } from '../services/swarmService';

const OperationalSwarm = () => {
  const [delegationForm, setDelegationForm] = React.useState({ agents: [], context: '' });
  const [isDeploying, setIsDeploying] = React.useState(false);
  const [deployFailed, setDeployFailed] = React.useState(false);

  const handleDeploySwarm = async (e) => {
    e.preventDefault();
    if (delegationForm.agents.length === 0 || !delegationForm.context) {
       toast.error('Please complete all delegation fields.');
       return;
    }

    setIsDeploying(true);
    setDeployFailed(false);
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000); // 15000ms timeout

    try {
      await swarmService.deploySwarmAgent(
        delegationForm.agents.join(", "),
        delegationForm.context,
        controller.signal
      );
      clearTimeout(timeoutId);

      await activityService.logSystemActivity(`AI Swarm deployed: ${delegationForm.agents.join(", ")}. Context: ${delegationForm.context.substring(0, 50)}...`);

      toast.success(`AI Swarm '${delegationForm.agents.join(", ")}' deployed to edge worker.`);
      setDelegationForm({ agents: [], context: '' });
      setDeployFailed(false);
    } catch (err) {
      clearTimeout(timeoutId);
      if (err.name === 'AbortError') {
        activityService.logSystemActivity(`ERROR: AI Swarm initialization timed out at the edge. Agent: ${delegationForm.agents.join(", ")}`).catch(console.error);
        toast.error('AI Swarm initialization timed out at the edge. Please retry.');
        setDeployFailed(true);
      } else {
        console.error(err);
        toast.error('Failed to deploy Swarm');
        setDeployFailed(true);
      }
    } finally {
      setIsDeploying(false);
    }
  };
  const { tasks, toggleTaskStatus, deals, contacts, refreshData } = useCrm();

  useEffect(() => {
    const channel = supabase
      .channel('operational-swarm-tasks-sync')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'tasks'
      }, (payload) => {
        console.log('Realtime task event received in OperationalSwarm:', payload);
        refreshData(true);
      })
      .subscribe((status, err) => {
        if (err || status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
          logToAsguardDLQ({ type: 'REALTIME_ERROR', message: 'operational-swarm-tasks-sync error', error: err, status });
        }
      });

    return () => { supabase.removeChannel(channel); };
  }, [refreshData]);

  const getEntityName = (task) => {
    if (task.deal_id) return deals.find(d => d.id === task.deal_id)?.title;
    if (task.contact_id) {
      const c = contacts.find(c => c.id === task.contact_id);
      return c ? `${c.first_name} ${c.last_name}` : 'Unknown';
    }
    return 'Nexus Core';
  };

  return (
    <div className="p-8 max-w-7xl mx-auto w-full space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight">Operational Swarm</h1>
          <p className="text-slate-500 text-sm mt-1">Action items generated by Onyx Mk3 and manual triggers.</p>
        </div>
        <div className="flex space-x-3">
          <div className="bg-white border border-slate-200 rounded-xl px-4 py-2 flex items-center space-x-4 shadow-sm">
            <div className="text-center">
              <div className="text-[10px] font-black text-slate-400 uppercase">Pending</div>
              <div className="text-sm font-black text-slate-900">{tasks.filter(t => t.status === 'TODO').length}</div>
            </div>
            <div className="w-px h-6 bg-slate-100"></div>
            <div className="text-center">
              <div className="text-[10px] font-black text-slate-400 uppercase">AI Tasks</div>
              <div className="text-sm font-black text-indigo-600">{tasks.filter(t => t.type === 'AI_SUGGESTION').length}</div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <h2 className="text-lg font-black text-slate-900 tracking-tight mb-4 flex items-center space-x-2">
              <SafeIcon icon={FiIcons.FiActivity} className="text-indigo-600" />
              <span>Active Swarm Dispatches</span>
            </h2>
            <div className="bg-slate-50 border border-slate-200 border-dashed rounded-xl p-8 flex flex-col items-center justify-center text-center">
              <SafeIcon icon={FiIcons.FiInbox} className="text-3xl text-slate-300 mb-3" />
              <p className="text-slate-500 font-medium">No active dispatches in the matrix.</p>
              <p className="text-xs text-slate-400 mt-1">Onyx Mk3 will generate tasks here based on deal activity.</p>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-black text-slate-900 tracking-tight mb-4 flex items-center space-x-2">
              <SafeIcon icon={FiIcons.FiList} className="text-slate-600" />
              <span>Task Queue</span>
            </h2>
          {tasks.map(task => (
            <div key={task.id} className={`bg-white p-5 rounded-2xl border transition-all flex items-center space-x-4 ${task.status === 'DONE' ? 'opacity-50 grayscale' : 'border-slate-200 shadow-sm hover:border-indigo-200'}`}>
              <button 
                onClick={() => toggleTaskStatus(task.id)}
                className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors ${task.status === 'DONE' ? 'bg-emerald-500 border-emerald-500 text-white' : 'border-slate-200 hover:border-indigo-500'}`}
              >
                {task.status === 'DONE' && <SafeIcon icon={FiIcons.FiCheck} className="text-sm" />}
              </button>
              
              <div className="flex-1">
                <div className="flex items-center space-x-2">
                  <span className={`text-[9px] font-black px-1.5 py-0.5 rounded uppercase ${task.type === 'AI_SUGGESTION' ? 'bg-indigo-100 text-indigo-600' : 'bg-slate-100 text-slate-500'}`}>
                    {task.type.replace('_', ' ')}
                  </span>
                  <span className={`text-[9px] font-black px-1.5 py-0.5 rounded uppercase ${task.priority === 'HIGH' ? 'bg-rose-100 text-rose-600' : 'bg-amber-100 text-amber-600'}`}>
                    {task.priority}
                  </span>
                </div>
                <h3 className={`font-bold mt-1 ${task.status === 'DONE' ? 'line-through text-slate-400' : 'text-slate-800'}`}>{task.title}</h3>
                <div className="flex items-center space-x-3 mt-1 text-[10px] font-bold text-slate-400 uppercase tracking-tighter">
                  <span className="flex items-center space-x-1"><SafeIcon icon={FiIcons.FiLink} className="text-[10px]"/> <span>{getEntityName(task)}</span></span>
                  <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
                  <span className="flex items-center space-x-1"><SafeIcon icon={FiIcons.FiClock} className="text-[10px]"/> <span>Due {task.due_date}</span></span>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <button className="p-2 text-slate-400 hover:text-indigo-600 transition-colors">
                  <SafeIcon icon={FiIcons.FiEdit3} />
                </button>
                <button className="p-2 text-slate-400 hover:text-rose-600 transition-colors">
                  <SafeIcon icon={FiIcons.FiTrash2} />
                </button>
              </div>
            </div>
          ))}
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-indigo-600 rounded-2xl p-6 text-white shadow-xl shadow-indigo-100 relative overflow-hidden">
            <div className="relative z-10">
              <h4 className="text-lg font-black mb-2">Swarm Performance</h4>
              <p className="text-indigo-100 text-sm mb-6">AI-generated tasks have a 84% completion-to-revenue conversion rate.</p>
              <div className="flex items-end space-x-2">
                <div className="text-3xl font-black">12.4h</div>
                <div className="text-[10px] font-bold uppercase text-indigo-200 mb-1.5">Avg. Response Time</div>
              </div>
            </div>
            <SafeIcon icon={FiIcons.FiZap} className="absolute -bottom-6 -right-6 text-9xl text-white/10" />
          </div>


          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm mb-8">
            <h4 className="text-sm font-black text-slate-900 mb-4 flex items-center space-x-2">
              <SafeIcon icon={FiIcons.FiCpu} className="text-indigo-500" />
              <span>AI Task Swarm Delegation</span>
            </h4>
            <form onSubmit={handleDeploySwarm} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Select Target AI Agents</label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {["Lead Qualifier AI", "Retention AI", "Billing AI", "Support Triage AI"].map(agent => (
                    <label key={agent} className={`flex items-center space-x-3 p-3 rounded-lg border cursor-pointer transition-all ${delegationForm.agents.includes(agent) ? "bg-indigo-50 border-indigo-200" : "bg-white border-slate-200 hover:border-indigo-100"}`}>
                      <input type="checkbox" className="form-checkbox h-4 w-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500" checked={delegationForm.agents.includes(agent)} onChange={(e) => { const currentAgents = [...delegationForm.agents]; if (e.target.checked) { currentAgents.push(agent); } else { const index = currentAgents.indexOf(agent); if (index > -1) currentAgents.splice(index, 1); } setDelegationForm({ ...delegationForm, agents: currentAgents }); setDeployFailed(false); }} disabled={isDeploying} />
                      <span className={`text-sm font-bold ${delegationForm.agents.includes(agent) ? "text-indigo-900" : "text-slate-600"}`}>{agent}</span>
                    </label>
                  ))}
                </div>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Delegation Context</label>
                <textarea
                  rows="3"
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                  placeholder="Provide context and constraints for the AI agent..."
                  value={delegationForm.context}
                  onChange={(e) => {
                    setDelegationForm({...delegationForm, context: e.target.value});
                    setDeployFailed(false);
                  }}
                  disabled={isDeploying}
                ></textarea>
              </div>
              <button
                type="submit"
                disabled={isDeploying}
                className={`w-full py-2 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-indigo-100 disabled:opacity-50 ${deployFailed ? 'bg-rose-600 hover:bg-rose-700' : 'bg-slate-900 hover:bg-indigo-600'}`}
              >
                {isDeploying ? 'Deploying to Edge...' : (deployFailed ? 'Retry Deployment' : 'Deploy Swarm')}
              </button>
            </form>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">

            <h4 className="text-sm font-black text-slate-900 mb-4 flex items-center space-x-2">
              <SafeIcon icon={FiIcons.FiCpu} className="text-indigo-500" />
              <span>Onyx Insights Feed</span>
            </h4>
            <div className="space-y-4">
              {[
                "Marcus Chen updated LinkedIn profile (New Role: VP Operations)",
                "Apex Solar Q2 financials released (Revenue +15% YoY)",
                "Nexus Logistics hiring 14 new fleet managers"
              ].map((insight, i) => (
                <div key={i} className="flex items-start space-x-3 py-2 border-b border-slate-50 last:border-0">
                  <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0"></div>
                  <p className="text-xs text-slate-600 leading-relaxed">{insight}</p>
                </div>
              ))}
            </div>
            <button className="w-full mt-6 py-2 border border-slate-200 rounded-xl text-[10px] font-black text-slate-500 uppercase hover:bg-slate-50 transition-all">
              Initialize Enrichment Bridge
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OperationalSwarm;
